# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

als_implicit <- function(mat, X, XtX, Y, n_threads) {
    invisible(.Call('pkgrecommendr_als_implicit', PACKAGE = 'pkgrecommendr', mat, X, XtX, Y, n_threads))
}

als_loss <- function(mat, X, Y, lambda, n_threads) {
    .Call('pkgrecommendr_als_loss', PACKAGE = 'pkgrecommendr', mat, X, Y, lambda, n_threads)
}

get_nn <- function(x, k, n_threads) {
    .Call('pkgrecommendr_get_nn', PACKAGE = 'pkgrecommendr', x, k, n_threads)
}

top_k_indices_byrow <- function(x, mat, k, n_threads) {
    .Call('pkgrecommendr_top_k_indices_byrow', PACKAGE = 'pkgrecommendr', x, mat, k, n_threads)
}

